name: WordPress.com Deploy Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Build
        run: bash scripts/build.sh
      - name: Test
        run: bash scripts/test.sh

  validate-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Verify required WordPress.com configuration files
        run: |
          required_files=(
            "WORDPRESS-COM-DEPLOYMENT.md"
            "readme.txt"
            "treasury-tech-portal.php"
            ".wordpress-com/config.json"
            ".wordpress-com/deployment.yml"
          )
          missing=0
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Missing required file: $file" >&2
              missing=1
            fi
          done
          if [ "$missing" -ne 0 ]; then
            exit 1
          fi
