name: WordPress.com Deploy Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl
          coverage: xdebug
          tools: composer
          
      - name: Install dependencies
        run: composer install --dev --no-interaction

      - name: Set PHPCS installed paths
        run: vendor/bin/phpcs --config-set installed_paths vendor/phpcsstandards/phpcsutils,vendor/phpcsstandards/phpcsextra,vendor/wp-coding-standards/wpcs

      - name: Run PHP CodeSniffer
        run: composer run cs
        
      - name: Run PHPStan
        run: composer run analyze
        
      - name: Run PHPUnit tests
        run: composer run test

  build-and-validate:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install npm dependencies
        run: npm ci
        
      - name: Build assets
        run: npm run build
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Build
        run: bash scripts/build.sh
        
      - name: Test
        run: bash scripts/test.sh
